data<- read.delim("household_power_consumption.txt", sep=";", dec=".", na.strings="?", skip = 66636, nrows=2880)
names(data) <-tolower(c("Date", "Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dt <- paste(data$date, data$time, sep=" " )
dt<- strptime(dt, format = "%d/%m/%Y %H:%M:%S")
png(filename="plot2.png", width=480, height=480)
plot(dt, data$global_active_power, type="l", ylab="Global Active Power (kilowatts)", xlab=NA)
dev.off()